CREATE TABLE [dbo].[QC_EGMS_ARCHIVAL_ERROR_LOG](
	[QC_EGMS_ARCHIVAL_ERROR_LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[QC_EGMS_ARCHIVAL_CONFIG_ID] [int] NULL,
	[ERROR_DESCRIPTION] [varchar](max) NULL,
	[ERROR_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[QC_EGMS_ARCHIVAL_ERROR_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[QC_EGMS_ARCHIVAL_EXECUTION_LOG](
	[QC_EGMS_ARCHIVAL_EXECUTION_LOG_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[QC_EGMS_ARCHIVAL_CONFIG_ID] [int] NULL,
	[NUMBER_OF_RECORDS_AFFECTED] [int] NULL,
	[OPERATION_TYPE_ID] TINYINT,
	[TABLE_NAME] [varchar](200) NULL,
	[MIN_VALUE] VARCHAR(200),
	[MAX_VALUE] VARCHAR(200),
	[EXECUTION_START_TIME] [datetime] NULL,
	[EXECUTION_END_TIME] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[QC_EGMS_ARCHIVAL_EXECUTION_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

