SET IDENTITY_INSERT [dbo].[QC_EGMS_ARCHIVAL_CONFIG] ON 

INSERT [dbo].[QC_EGMS_ARCHIVAL_CONFIG] ([QC_EGMS_ARCHIVAL_CONFIG_ID], [ARCHIVAL_TABLE_NAME], [PRIMARY_ARCHIVAL_COLUMN_NAME], [JOIN_TABLE_NAMES], [PREDICATE_CONDITION], [JOIN_TYPE], [JOIN_COLUMNS], [BATCH_SIZE], [IS_RUNNING], [IS_ENABLED], [LINKED_SERVER_NAME], [ARCHIVE_DATABASE_NAME], [ARCHIVE_SCHEMA_NAME], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [IS_APPROVED], [APPROVED_BY], [APPROVED_DATE], [DESCRIPTION], [IS_RUNNABLE], [EMAIL_RECIPIENTS], [JOB_START_TIME], [JOB_END_TIME], [SCHEDULE_FREQUENCY_IN_DAYS], [MAX_RECORDS_TO_ARCHIVE], [ARCHIVE_DATE_COLUMN]) 
VALUES (1, N'dbo.QC_EGMS_XACTION_LOG', N'XACTIONID', N'QC_EGMS_XACTION_LOG', N'Where XactionTypeID = 6', NULL, NULL, 1000, 0, 1, N'AMZGCARCHIVALDB', N'Qwikcilver_eGMS_Archive', N'dbo', 1, GETDATE(), NULL, NULL, 1, 1, GETDATE(), N'Xaction Achival where the transaction type is of balance enquiry and that are atleast 2 months old', 1, NULL, CAST(N'03:00:00' AS Time), CAST(N'05:00:00' AS Time), 1, 140928396, N'XACTIONDATEATSERVER')

INSERT [dbo].[QC_EGMS_ARCHIVAL_CONFIG] ([QC_EGMS_ARCHIVAL_CONFIG_ID], [ARCHIVAL_TABLE_NAME], [PRIMARY_ARCHIVAL_COLUMN_NAME], [JOIN_TABLE_NAMES], [PREDICATE_CONDITION], [JOIN_TYPE], [JOIN_COLUMNS], [BATCH_SIZE], [IS_RUNNING], [IS_ENABLED], [LINKED_SERVER_NAME], [ARCHIVE_DATABASE_NAME], [ARCHIVE_SCHEMA_NAME], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [IS_APPROVED], [APPROVED_BY], [APPROVED_DATE], [DESCRIPTION], [IS_RUNNABLE], [EMAIL_RECIPIENTS], [JOB_START_TIME], [JOB_END_TIME], [SCHEDULE_FREQUENCY_IN_DAYS], [MAX_RECORDS_TO_ARCHIVE], [ARCHIVE_DATE_COLUMN]) 
VALUES (2, N'dbo.QC_EGMS_XACTION_RESPONSE_TIME', N'XACTIONRESPONSETIMEID', N'QC_EGMS_XACTION_RESPONSE_TIME', N'where XACTIONRESPONSETIMEID  < 826376954', NULL, NULL, 1000, 0, 1, N'AMZGCARCHIVALDB', N'Qwikcilver_eGMS_Archive', N'dbo', 1, GETDATE(), NULL, NULL, 1, 1, GETDATE(), N' Archive all Response time records that are older than 1 month', 1, NULL, CAST(N'03:00:00' AS Time), CAST(N'05:00:00' AS Time), 1, 140928396, NULL)

INSERT [dbo].[QC_EGMS_ARCHIVAL_CONFIG] ([QC_EGMS_ARCHIVAL_CONFIG_ID], [ARCHIVAL_TABLE_NAME], [PRIMARY_ARCHIVAL_COLUMN_NAME], [JOIN_TABLE_NAMES], [PREDICATE_CONDITION], [JOIN_TYPE], [JOIN_COLUMNS], [BATCH_SIZE], [IS_RUNNING], [IS_ENABLED], [LINKED_SERVER_NAME], [ARCHIVE_DATABASE_NAME], [ARCHIVE_SCHEMA_NAME], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [IS_APPROVED], [APPROVED_BY], [APPROVED_DATE], [DESCRIPTION], [IS_RUNNABLE], [EMAIL_RECIPIENTS], [JOB_START_TIME], [JOB_END_TIME], [SCHEDULE_FREQUENCY_IN_DAYS], [MAX_RECORDS_TO_ARCHIVE], [ARCHIVE_DATE_COLUMN]) 
VALUES (3, N'dbo.QC_EGMS_VALIDATION_LOG', N'VALIDATIONLOGID', N'QC_EGMS_VALIDATION_LOG', N'where XACTIONDATEATSERVER < DATEADD(MONTH,-6,getdate())', NULL, NULL, 1000, 0, 1, N'AMZGCARCHIVALDB', N'Qwikcilver_eGMS_Archive', N'dbo', 1, GETDATE(), NULL, NULL, 1, 1, GETDATE(), N' Archival all Validation log records that are older than six (6) months ', 1, NULL, CAST(N'03:00:00' AS Time), CAST(N'05:00:00' AS Time), 1, 140928396, NULL)

INSERT [dbo].[QC_EGMS_ARCHIVAL_CONFIG] ([QC_EGMS_ARCHIVAL_CONFIG_ID], [ARCHIVAL_TABLE_NAME], [PRIMARY_ARCHIVAL_COLUMN_NAME], [JOIN_TABLE_NAMES], [PREDICATE_CONDITION], [JOIN_TYPE], [JOIN_COLUMNS], [BATCH_SIZE], [IS_RUNNING], [IS_ENABLED], [LINKED_SERVER_NAME], [ARCHIVE_DATABASE_NAME], [ARCHIVE_SCHEMA_NAME], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [IS_APPROVED], [APPROVED_BY], [APPROVED_DATE], [DESCRIPTION], [IS_RUNNABLE], [EMAIL_RECIPIENTS], [JOB_START_TIME], [JOB_END_TIME], [SCHEDULE_FREQUENCY_IN_DAYS], [MAX_RECORDS_TO_ARCHIVE], [ARCHIVE_DATE_COLUMN]) 
VALUES (4, N'dbo.QC_EGMS_XACTION_LOG', N'XACTIONID', N'QC_EGMS_XACTION_LOG,QC_EGMS_CARDS,QC_EGMS_GIFTCARD_STOREDVALUES', N'WHERE QC_EGMS_CARDS.CARDEXPIRY < DATEADD(MONTH,-12,GETDATE()) AND QC_EGMS_GIFTCARD_STOREDVALUES.OUTSTANDINGGIFTVALUE= 0', N'INNER,INNER', N'QC_EGMS_XACTION_LOG.CARDID=QC_EGMS_CARDS.CARDID,QC_EGMS_XACTION_LOG.CARDID=QC_EGMS_GIFTCARD_STOREDVALUES.CARDID', 1000, 0, 1, N'AMZGCARCHIVALDB', N'Qwikcilver_eGMS_Archive', N'dbo', 1, GETDATE(), NULL, NULL, 1, 1, GETDATE(), N'Xaction Achival for cards that have expired more than an year and have zero card balance', 1, NULL, CAST(N'03:00:00' AS Time), CAST(N'05:00:00' AS Time), 1, 140928396, N'XACTIONDATEATSERVER')

INSERT [dbo].[QC_EGMS_ARCHIVAL_CONFIG] ([QC_EGMS_ARCHIVAL_CONFIG_ID], [ARCHIVAL_TABLE_NAME], [PRIMARY_ARCHIVAL_COLUMN_NAME], [JOIN_TABLE_NAMES], [PREDICATE_CONDITION], [JOIN_TYPE], [JOIN_COLUMNS], [BATCH_SIZE], [IS_RUNNING], [IS_ENABLED], [LINKED_SERVER_NAME], [ARCHIVE_DATABASE_NAME], [ARCHIVE_SCHEMA_NAME], [CREATED_BY], [CREATED_DATE], [MODIFIED_BY], [MODIFIED_DATE], [IS_APPROVED], [APPROVED_BY], [APPROVED_DATE], [DESCRIPTION], [IS_RUNNABLE], [EMAIL_RECIPIENTS], [JOB_START_TIME], [JOB_END_TIME], [SCHEDULE_FREQUENCY_IN_DAYS], [MAX_RECORDS_TO_ARCHIVE], [ARCHIVE_DATE_COLUMN]) 
VALUES (5, N'dbo.QC_EGMS_APPROVAL_CODE', N'APPROVALCODE', N'QC_EGMS_APPROVAL_CODE', N'where  (1=1)', NULL, NULL, 1000, 0, 1, N'AMZGCARCHIVALDB', N'Qwikcilver_eGMS_Archive', N'dbo', 1, GETDATE(), NULL, NULL, 1, 1, GETDATE(), N'Archival of all Approval codes', 1, NULL, CAST(N'03:00:00' AS Time), CAST(N'05:00:00' AS Time), 1, 140928396, NULL)

SET IDENTITY_INSERT [dbo].[QC_EGMS_ARCHIVAL_CONFIG] OFF



UPDATE dbo.[QC_EGMS_ARCHIVAL_CONFIG]  SET IS_ENABLED = 0 where QC_EGMS_ARCHIVAL_CONFIG_ID IN (1,4)



INSERT INTO dbo.QC_EGMS_ARCHIVAL_EMAIL_CONFIG(Email,[TO],[CC])
SELECT 'arjun.bs_conslt@qwikcilver.com',1,0
UNION  ALL 
SELECT 'ravishankara.beedige@qwikcilver.com',1,0	
UNION  ALL 
SELECT 'pradeep.kumar@qwikcilver.com',1,0	
GO

INSERT INTO dbo.QC_EGMS_ARCHIVAL_OPERATION_TYPE_LK
SELECT 1,'INSERT'
UNION 
SELECT 2,'DELETE'
GO

--SEED DATA ---

	INSERT INTO dbo.QC_EGMS_ARCHIVAL_GLOBAL_CONFIG
	SELECT 1 , 'SERVER_DATE','Date Older than 100 days','< DATEADD(MONTH, -2, getdate())',NULL

	INSERT INTO dbo.QC_EGMS_ARCHIVAL_GLOBAL_CONFIG
	SELECT 2 , 'ARCHIVE_CHILD_TABLES','Should the Child Tables be Archived or not',NULL,'Y'

--SEED DATA ---



/****** Object:  Synonym [dbo].[QC_EGMS_ARCHIVAL_ERROR_LOG_Syn]    Script Date: 1/10/2019 3:00:14 PM ******/
CREATE SYNONYM [dbo].[QC_EGMS_ARCHIVAL_ERROR_LOG_Syn] FOR [AMZGCARCHIVALDB].[Qwikcilver_eGMS_Archive].[dbo].[QC_EGMS_ARCHIVAL_ERROR_LOG]
GO



/****** Object:  Synonym [dbo].[QC_EGMS_ARCHIVAL_EXECUTION_LOG_Syn]    Script Date: 1/10/2019 3:00:36 PM ******/
CREATE SYNONYM [dbo].[QC_EGMS_ARCHIVAL_EXECUTION_LOG_Syn] FOR [AMZGCARCHIVALDB].[Qwikcilver_eGMS_Archive].[dbo].[QC_EGMS_ARCHIVAL_EXECUTION_LOG]
GO


