--select TABLE_NAME,COLUMN_NAME,DATA_TYPE from INFORMATION_SCHEMA.COLUMNS where COLUMN_NAME IN
--(
--'LinkId'
--)
-- order by COLUMN_NAME

SELECT * FROM INFORMATION_SCHEMA.COlumns ic  WHERE  EXISTS 
(
	SELECT 1 FROM 
	(
		SELECT COLUMN_NAME , COUNT(DATA_TYPE) as DistinctDataTypes FROM 
		(
			SELECT 
				COLUMN_NAME,DATA_TYPE, count(1) as cnt  FROM INFORMATION_SCHEMA.columns GROUP BY COLUMN_NAME,DATA_TYPE 
			--having 
			--	COLUMN_NAME = 'LinkID'
		)A
	Group by COLUMN_NAME  HAVING COUNT(DATA_TYPE)> 1 
	)B
	WHERE ic.COLUMN_NAME = B.COLUMN_NAME
)
Order by COLUMN_NAME