CREATE NONCLUSTERED INDEX [IX_AssetCommentHistory_EndTime_Purge] ON [dbo].[AssetCommentHistory](Shift_EndTime ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_InstructionCommentsHistory_Instruction_InstructionId_Purge] ON [dbo].[InstructionCommentsHistory](Instruction_InstructionId ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_InstructionsActionHistoryHistory_Instructions_InstructionID_Purge] ON [dbo].[InstructionsActionHistoryHistory](Instructions_InstructionID ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_InstructionsHistory_ActualEndTime_Purge] ON [dbo].[InstructionsHistory](ActualEndTime ASC) INCLUDE (InstructionId, State_StateId)WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_LimitInstructionDetailsHistory_Instruction_InstructionId_Purge] ON [dbo].[LimitInstructionDetailsHistory](Instruction_InstructionId ASC) INCLUDE (LimitInstructionDetailsHistory_PK_ID)WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_ShiftSummaryCommentHistory_Shift_EndTime_Purge] ON [dbo].[ShiftSummaryCommentHistory](Shift_EndTime ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_ShiftSummaryDisplayDataHistory_Shift_EndTime_Purge] ON [dbo].[ShiftSummaryDisplayDataHistory](Shift_EndTime ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_StandingOrderCommentsHistory_FK_StandingOrder_StandingOrder_PK_ID_Purge] ON [dbo].[StandingOrderCommentsHistory](StandingOrder_StandingOrder_PK_ID ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_StandingOrdersActionHistoryHistory_FK_StandingOrder_StandingOrder_PK_ID_Purge] ON [dbo].[StandingOrdersActionHistoryHistory](StandingOrder_StandingOrder_PK_ID ASC) INCLUDE (StandingOrdersActionHistoryHistory_PK_ID)WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_StandingOrdersHistory_ActualEndTime_Purge] ON [dbo].[StandingOrdersHistory](ActualEndTime ASC) INCLUDE (StandingOrder_PK_ID)WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_StandingOrdersHistory_StandingOrder_PK_ID_ActualEndTime_Purge] ON [dbo].[StandingOrdersHistory](StandingOrder_PK_ID ASC, ActualEndTime ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_TagMonitoringStatusHistories_DownTimeEndDownTimeEndDownTimeEnd_Purge] ON [dbo].[TagMonitoringStatusHistories](DownTimeEnd ASC) INCLUDE (TagMonitoringStatusHistory_PK_ID)WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_TaskActionHistoriesHistory_Task_Task_PK_Id_Purge] ON [dbo].[TaskActionHistoriesHistory](Task_Task_PK_Id ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_TaskAssigneesHistory_Task_Task_PK_Id_Purge] ON [dbo].[TaskAssigneesHistory](Task_Task_PK_Id ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_TaskNoteAssociationsHistory_Task_Task_PK_Id_Purge] ON [dbo].[TaskNoteAssociationsHistory](Task_Task_PK_Id ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_TaskNotesHistory_TaskNote_PK_ID_Purge] ON [dbo].[TaskNotesHistory](TaskNote_PK_ID ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_TasksHistory_ActualEndTime_Purge] ON [dbo].[TasksHistory](ActualEndTime ASC) INCLUDE (Task_PK_Id)WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_TasksHistory_SourceType_ActualEndTime_Purge] ON [dbo].[TasksHistory](SourceType ASC, ActualEndTime ASC) INCLUDE (Task_PK_Id)WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_TasksHistory_Task_PK_Id_Purge] ON [dbo].[TasksHistory](Task_PK_Id ASC) WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF, FILLFACTOR = 100) ON [PRIMARY];
 


