USE MASTER
GO
CREATE DATABASE MSSQLTIPS
GO
USE MSSQLTIPS
GO
CREATE TABLE DBO.EMPLOYEE
(
EMPLOYEEID INT IDENTITY(1,1),
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
DATE_HIRED DATETIME NOT NULL,
IS_ACTIVE BIT NOT NULL DEFAULT 1,
CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEEID),
CONSTRAINT UQ_EMPLOYEE_LASTNAME UNIQUE (LASTNAME, FIRSTNAME)
)
GO
INSERT INTO DBO.EMPLOYEE (FIRSTNAME,LASTNAME,DATE_HIRED)
SELECT 'George', 'Washington', '1999-03-15'
GO
INSERT INTO DBO.EMPLOYEE (FIRSTNAME,LASTNAME,DATE_HIRED)
SELECT 'Benjamin', 'Franklin', '2001-07-05'
GO
INSERT INTO DBO.EMPLOYEE (FIRSTNAME,LASTNAME,DATE_HIRED)
SELECT 'Thomas', 'Jefferson', '2002-11-10'
GO

-- List data and index pages allocated to the EMPLOYEE table
DBCC IND('MSSQLTIPS',EMPLOYEE,-1)
GO


DBCC TRACEON(3604)
GO
DBCC PAGE('MSSQLTIPS',1,312,3) WITH TABLERESULTS
GO

DBCC TRACEON(3604)
GO
DBCC PAGE('MSSQLTIPS',1,320,3) WITH TABLERESULTS
GO


ALTER TABLE DBO.EMPLOYEE DROP CONSTRAINT PK_EMPLOYEE
GO
ALTER TABLE DBO.EMPLOYEE ADD CONSTRAINT PK_EMPLOYEE
PRIMARY KEY NONCLUSTERED (EMPLOYEEID)
GO

DBCC IND('MSSQLTIPS',EMPLOYEE,-1)

DBCC PAGE('MSSQLTIPS',1,320,3) WITH TABLERESULTS
GO

DBCC PAGE('MSSQLTIPS',1,360,3) WITH TABLERESULTS
GO


DBCC CHECKDB ('MSDB') WITH NO_Infomsgs


DBCC CHECKDB (KinetEcoDW) WITH NO_INFOMSGS, ALL_ERRORMSGS;


---Example of rebuilding an index 
USE AdventureWorks2012;   
GO  
DBCC DBREINDEX ('HumanResources.Employee', PK_Employee_BusinessEntityID,80);  
GO 

